# Generated by Django 2.2.16 on 2023-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230502_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите файл', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
