# Generated by Django 2.2.16 on 2023-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230502_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст коментария', verbose_name='Комментарий'),
        ),
    ]
